version: "2"

linters:
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - errcheck
          - unused
          - gosimple

      - text: "Error return value of .*(Close|Remove|Rename|Write|WriteMessage|SetWriteDeadline)"
        linters:
          - errcheck

      - text: "SA1019: grpc.Dial is deprecated"
        linters:
          - staticcheck
