git submodule add https://github.com/obra/superpowers.git frameworks/superpowers
git submodule add https://github.com/automazeio/ccpm.git frameworks/ccpm
git submodule add https://github.com/mem0ai/mem0.git memory/mem0
git submodule add https://github.com/campfirein/cipher.git memory/cipher
git submodule add https://github.com/bartwisch/MCPRules.git mcp-servers/MCPRules
git submodule add https://github.com/upstash/context7.git mcp-servers/context7
git submodule add https://github.com/Minidoracat/mcp-feedback-enhanced.git mcp-servers/mcp-feedback-enhanced
git submodule add https://github.com/github/github-mcp-server.git mcp-servers/github-mcp-server
git submodule add https://github.com/microsoft/playwright-mcp.git mcp-servers/playwright-mcp
git submodule add https://github.com/hangwin/mcp-chrome.git mcp-servers/mcp-chrome
git submodule add https://github.com/ChromeDevTools/chrome-devtools-mcp.git mcp-servers/chrome-devtools-mcp
git submodule add https://github.com/MladenSU/cli-mcp-server.git mcp-servers/cli-mcp-server
