-- Add CHECK constraint for tickets.slug.
--
-- Tickets use a different slug format than organizations/loops:
--   ^[A-Z][A-Z0-9]*-[0-9]+$  e.g. "AM-123", "TICKET-1", "PROJ-42"
-- They are auto-generated by the ticket service from a per-repository prefix
-- and a monotonic counter — never user-supplied — so collision and format
-- violations should not occur in practice. This constraint is defense in depth.
--
-- NOT VALID skips checking existing rows. New inserts/updates are enforced.
--
-- Audit legacy violators with:
--   SELECT id, slug FROM tickets WHERE slug !~ '^[A-Z][A-Z0-9]*-[0-9]+$';

ALTER TABLE tickets
  ADD CONSTRAINT tickets_slug_format
  CHECK (slug ~ '^[A-Z][A-Z0-9]*-[0-9]+$' AND length(slug) BETWEEN 3 AND 50)
  NOT VALID;
