/* eslint-disable */
/* prettier-ignore */
/**
 * AUTO-GENERATED by clients/desktop/scripts/gen-ipc-tests.ts.
 *
 * Source of truth: `#[napi]` annotations in
 * clients/core/crates/node-bridge/src/.
 *
 * Regenerate:
 *   bazel build //clients/core/crates/node-bridge:node_bridge
 *   pnpm --filter desktop e2e:gen
 *
 * Do NOT edit by hand — changes will be overwritten on next regen.
 */

export function initLogger(logDir: string, level: string): void;
export function logEvent(level: string, target: string, msg: string): void;

export class AppState {
  constructor(baseUrl: string, storageDir: string);
  apikeyCreateConnect(request: Array<number>): Promise<Array<number>>
  apikeyDeleteConnect(request: Array<number>): Promise<Array<number>>
  apikeyGetConnect(request: Array<number>): Promise<Array<number>>
  apikeyListConnect(request: Array<number>): Promise<Array<number>>
  apikeyRevokeConnect(request: Array<number>): Promise<Array<number>>
  apikeyUpdateConnect(request: Array<number>): Promise<Array<number>>
  appAutopilotAppendIteration(reqBytes: Array<number>): void
  appAutopilotApplyFetchedControllers(respBytes: Array<number>): void
  appAutopilotApplyFetchedCurrentController(respBytes: Array<number>): void
  appAutopilotApplyFetchedIterations(key: string, respBytes: Array<number>): void
  appAutopilotControllersJson(): string
  appAutopilotControllersProto(): Array<number>
  appAutopilotInsertController(reqBytes: Array<number>): void
  appAutopilotIterationsJson(key: string): string
  appAutopilotIterationsProto(key: string): Array<number>
  appAutopilotPatchController(reqBytes: Array<number>): void
  appAutopilotRemoveControllerProto(reqBytes: Array<number>): void
  appAutopilotSetCurrentControllerProto(reqBytes: Array<number>): void
  appAutopilotThinkingHistoryJson(key: string): string
  appAutopilotThinkingJson(key: string): string
  appAutopilotUpdateThinkingProto(reqBytes: Array<number>): void
  appAvailableRunnersJson(): string
  appAvailableRunnersProto(): Array<number>
  appChannelAdvanceLastRead(channelId: number, messageId: number): void
  appChannelApplyFetchedChannel(respBytes: Array<number>): void
  appChannelApplyFetchedChannels(respBytes: Array<number>): void
  appChannelApplyFetchedMembers(channelId: number, respBytes: Array<number>): void
  appChannelApplyFetchedMessages(channelId: number, respBytes: Array<number>): void
  appChannelApplyFetchedMessagesPrepend(channelId: number, respBytes: Array<number>): void
  appChannelApplyFetchedPods(channelId: number, respBytes: Array<number>): void
  appChannelApplyMessageEdited(reqBytes: Array<number>): void
  appChannelClearUnread(channelId: number): void
  appChannelGetLastReadId(channelId: number): number
  appChannelInsertChannel(reqBytes: Array<number>): void
  appChannelInsertMessage(reqBytes: Array<number>): void
  appChannelMentionCountsJson(): string
  appChannelMessagesJson(channelId: number): string
  appChannelPatchMemberCount(reqBytes: Array<number>): void
  appChannelPodsJson(channelId: number): string
  appChannelRemoveMember(reqBytes: Array<number>): void
  appChannelRemoveMessage(channelId: number, messageId: number): void
  appChannelReplaceMembers(reqBytes: Array<number>): void
  appChannelReplacePods(reqBytes: Array<number>): void
  appChannelReplaceUnreadCounts(reqBytes: Array<number>): void
  appChannelsJson(): string
  appChannelUnreadCountsJson(): string
  appCurrentRunnerJson(): string
  appCurrentRunnerProto(): Array<number>
  appGetMeshNodeJson(podKey: string): string
  appGetPodJson(podKey: string): string
  appGetPodProto(podKey: string): Array<number>
  appMeshReplaceTopology(reqBytes: Array<number>): void
  appPodApplyAppendedPods(respBytes: Array<number>): void
  appPodApplyFetchedPods(respBytes: Array<number>): void
  appPodInsertCreated(reqBytes: Array<number>): void
  appPodMarkTerminated(reqBytes: Array<number>): void
  appPodPatchPerpetual(reqBytes: Array<number>): void
  appPodRemove(podKey: string): void
  appPodsJson(): string
  appRunnerApplyFetched(respBytes: Array<number>): void
  appRunnerApplyFetchedAvailable(respBytes: Array<number>): void
  appRunnerApplyFetchedCurrent(respBytes: Array<number>): void
  appRunnerPatch(reqBytes: Array<number>): void
  appRunnerRemove(reqBytes: Array<number>): void
  appRunnerSetCurrent(reqBytes: Array<number>): void
  appRunnersJson(): string
  appRunnersProto(): Array<number>
  appSelectChannel(id: number | undefined | null): void
  appSetCurrentChannel(id: number | undefined | null): void
  appSetCurrentUser(userId: number | undefined | null): void
  authApplySessionProto(reqBytes: Array<number>): void
  authBootstrap(): Promise<string>
  authBootstrapProto(): Promise<Array<number>>
  authClearSession(): void
  authConnectForgotPasswordConnect(request: Array<number>): Promise<Array<number>>
  authConnectLoginConnect(request: Array<number>): Promise<Array<number>>
  authConnectLogoutConnect(request: Array<number>): Promise<Array<number>>
  authConnectOauthCallbackConnect(request: Array<number>): Promise<Array<number>>
  authConnectOauthRedirectConnect(request: Array<number>): Promise<Array<number>>
  authConnectRefreshTokenConnect(request: Array<number>): Promise<Array<number>>
  authConnectRegisterConnect(request: Array<number>): Promise<Array<number>>
  authConnectResendVerificationConnect(request: Array<number>): Promise<Array<number>>
  authConnectResetPasswordConnect(request: Array<number>): Promise<Array<number>>
  authConnectVerifyEmailConnect(request: Array<number>): Promise<Array<number>>
  authFetchOrganizations(): Promise<string>
  authFetchOrganizationsProto(): Promise<Array<number>>
  authGetCurrentOrgJson(): string | undefined | null
  authGetCurrentUserJson(): string | undefined | null
  authGetCurrentUserProto(): Array<number> | undefined | null
  authGetExpiresAt(): number | undefined | null
  authGetOrganizationsJson(): string
  authGetToken(): string | undefined | null
  authIsAuthenticated(): boolean
  authLogin(email: string, password: string): Promise<string>
  authLoginProto(email: string, password: string): Promise<Array<number>>
  authLogout(): Promise<void>
  authRefreshToken(): Promise<string>
  authRefreshTokenProto(): Promise<Array<number>>
  authSetCurrentOrgProto(reqBytes: Array<number>): void
  authSetOrganizationsProto(reqBytes: Array<number>): void
  authSwitchOrg(slug: string): void
  bindingAcceptBindingConnect(request: Uint8Array): Promise<Uint8Array>
  bindingApproveScopesConnect(request: Uint8Array): Promise<Uint8Array>
  bindingCheckBindingConnect(request: Uint8Array): Promise<Uint8Array>
  bindingGetBoundPodsConnect(request: Uint8Array): Promise<Uint8Array>
  bindingGetPendingBindingsConnect(request: Uint8Array): Promise<Uint8Array>
  bindingListBindingsConnect(request: Uint8Array): Promise<Uint8Array>
  bindingRejectBindingConnect(request: Uint8Array): Promise<Uint8Array>
  bindingRequestBindingConnect(request: Uint8Array): Promise<Uint8Array>
  bindingRequestScopesConnect(request: Uint8Array): Promise<Uint8Array>
  bindingUnbindConnect(request: Uint8Array): Promise<Uint8Array>
  blockstoreApplyRemoteOp(reqBytes: Array<number>): Promise<void>
  blockstoreBacklinksJson(): Promise<string>
  blockstoreBlocksJson(): Promise<string>
  blockstoreCatchup(workspaceId: string): Promise<void>
  blockstoreEnsureDefaultWorkspace(): Promise<string>
  blockstoreGetBlockJson(id: string): Promise<string | undefined | null>
  blockstoreLastOpId(workspaceId: string): Promise<number>
  blockstoreLastOpIdsJson(): Promise<string>
  blockstoreListBacklinksJson(targetId: string): Promise<string>
  blockstoreListChildrenJson(parentId: string): Promise<string>
  blockstoreListWorkspaces(): Promise<string>
  blockstoreLoadSubtree(workspaceId: string, rootId: string): Promise<void>
  blockstoreLoadTypeDefs(workspaceId: string): Promise<void>
  blockstoreNestChildrenJson(): Promise<string>
  blockstoreProjectLocalOps(reqBytes: Array<number>): Promise<void>
  blockstoreRefsJson(): Promise<string>
  blockstoreReplaceWorkspaces(reqBytes: Array<number>): Promise<void>
  blockstoreSetLastOpId(workspaceId: string, id: number): Promise<void>
  blockstoreTypeDefsJson(workspaceId: string): Promise<string>
  blockstoreUpsertBlocks(reqBytes: Array<number>): Promise<void>
  blockstoreUpsertRefs(reqBytes: Array<number>): Promise<void>
  blockstoreUpsertWorkspace(reqBytes: Array<number>): Promise<void>
  blockstoreWorkspacesJson(): Promise<string>
  channelArchiveChannelConnect(request: Array<number>): Promise<Array<number>>
  channelCreateChannelConnect(request: Array<number>): Promise<Array<number>>
  channelDeleteChannelMessageConnect(request: Array<number>): Promise<Array<number>>
  channelEditChannelMessageConnect(request: Array<number>): Promise<Array<number>>
  channelGetChannelConnect(request: Array<number>): Promise<Array<number>>
  channelGetChannelUnreadCountsConnect(request: Array<number>): Promise<Array<number>>
  channelGetMessageReadByConnect(request: Array<number>): Promise<Array<number>>
  channelListChannelMembersConnect(request: Array<number>): Promise<Array<number>>
  channelListChannelMessagesConnect(request: Array<number>): Promise<Array<number>>
  channelListChannelsConnect(request: Array<number>): Promise<Array<number>>
  channelMarkChannelReadConnect(request: Array<number>): Promise<Array<number>>
  channelMarkChannelUnreadConnect(request: Array<number>): Promise<Array<number>>
  channelMuteChannelConnect(request: Array<number>): Promise<Array<number>>
  channelPinChannelConnect(request: Array<number>): Promise<Array<number>>
  channelSendChannelMessageConnect(request: Array<number>): Promise<Array<number>>
  channelUnarchiveChannelConnect(request: Array<number>): Promise<Array<number>>
  channelUpdateChannelConnect(request: Array<number>): Promise<Array<number>>
  envBundleCreateEnvBundleConnect(request: Array<number>): Promise<Array<number>>
  envBundleDeleteEnvBundleConnect(request: Array<number>): Promise<Array<number>>
  envBundleGetEnvBundleConnect(request: Array<number>): Promise<Array<number>>
  envBundleListEnvBundlesConnect(request: Array<number>): Promise<Array<number>>
  envBundleSetPrimaryEnvBundleConnect(request: Array<number>): Promise<Array<number>>
  envBundleUpdateEnvBundleConnect(request: Array<number>): Promise<Array<number>>
  eventsConnect(): Promise<void>
  eventsDisconnect(): Promise<void>
  eventsGetConnectionState(): Promise<string>
  eventsGetTick(): number
  eventsNudge(): Promise<void>
  eventsOnConnectionStateChange(callback: (err: unknown, arg: string) => void): Promise<number>
  eventsSubscribeAll(callback: (err: unknown, arg: string) => void): Promise<number>
  eventsUnsubscribe(id: number): Promise<void>
  extensionCreateSkillRegistryConnect(request: Array<number>): Promise<Array<number>>
  extensionDeleteSkillRegistryConnect(request: Array<number>): Promise<Array<number>>
  extensionInstallCustomMcpServerConnect(request: Array<number>): Promise<Array<number>>
  extensionInstallMcpFromMarketConnect(request: Array<number>): Promise<Array<number>>
  extensionInstallSkillFromGithubConnect(request: Array<number>): Promise<Array<number>>
  extensionInstallSkillFromMarketConnect(request: Array<number>): Promise<Array<number>>
  extensionInstallSkillFromUploadedFileConnect(request: Array<number>): Promise<Array<number>>
  extensionListMarketMcpServersConnect(request: Array<number>): Promise<Array<number>>
  extensionListMarketSkillsConnect(request: Array<number>): Promise<Array<number>>
  extensionListRepoMcpServersConnect(request: Array<number>): Promise<Array<number>>
  extensionListRepoSkillsConnect(request: Array<number>): Promise<Array<number>>
  extensionListSkillRegistriesConnect(request: Array<number>): Promise<Array<number>>
  extensionListSkillRegistryOverridesConnect(request: Array<number>): Promise<Array<number>>
  extensionPresignSkillUploadConnect(request: Array<number>): Promise<Array<number>>
  extensionSyncSkillRegistryConnect(request: Array<number>): Promise<Array<number>>
  extensionTogglePlatformRegistryConnect(request: Array<number>): Promise<Array<number>>
  extensionUninstallMcpServerConnect(request: Array<number>): Promise<Array<number>>
  extensionUninstallSkillConnect(request: Array<number>): Promise<Array<number>>
  extensionUpdateMcpServerConnect(request: Array<number>): Promise<Array<number>>
  extensionUpdateSkillConnect(request: Array<number>): Promise<Array<number>>
  fileUploadFile(fileData: Array<number>, filename: string, contentType: string): Promise<string>
  invitationAcceptInvitationConnect(request: Array<number>): Promise<Array<number>>
  invitationCreateInvitationConnect(request: Array<number>): Promise<Array<number>>
  invitationGetInvitationByTokenConnect(request: Array<number>): Promise<Array<number>>
  invitationListInvitationsConnect(request: Array<number>): Promise<Array<number>>
  invitationListPendingInvitationsConnect(request: Array<number>): Promise<Array<number>>
  invitationResendInvitationConnect(request: Array<number>): Promise<Array<number>>
  invitationRevokeInvitationConnect(request: Array<number>): Promise<Array<number>>
  localRunnerBinaryPath(): Promise<string>
  localRunnerFallbackVersion(): Promise<string>
  localRunnerHostTarget(): Promise<string | undefined | null>
  localRunnerInstallBinary(releaseUrl: string, expectedSha256: string | undefined | null): Promise<void>
  localRunnerInstalledVersion(): Promise<string | undefined | null>
  localRunnerIsInstalled(): Promise<boolean>
  localRunnerIsRegistered(): Promise<boolean>
  localRunnerLocalNodeId(): Promise<string | undefined | null>
  localRunnerRegister(token: string): Promise<void>
  localRunnerServiceInstall(): Promise<void>
  localRunnerServiceStart(): Promise<void>
  localRunnerServiceStatus(): Promise<string>
  localRunnerServiceStop(): Promise<void>
  localRunnerServiceUninstall(): Promise<void>
  meshBatchGetTicketPodsConnect(request: Uint8Array): Promise<Uint8Array>
  meshCreatePodForTicketConnect(request: Uint8Array): Promise<Uint8Array>
  meshFetchTopology(): Promise<Uint8Array>
  meshGetMeshTopologyConnect(request: Uint8Array): Promise<Uint8Array>
  meshGetTicketPodsConnect(request: Uint8Array): Promise<Uint8Array>
  promocodeGetRedemptionHistoryConnect(request: Array<number>): Promise<Array<number>>
  promocodeRedeemPromoCodeConnect(request: Array<number>): Promise<Array<number>>
  promocodeValidatePromoCodeConnect(request: Array<number>): Promise<Array<number>>
  relayBindPodListeners(podKey: string, onStatus: (err: unknown, arg: string) => void, onAcp: (err: unknown, arg: string) => void, listenerLeaseId: string): Promise<number>
  relayDisconnect(podKey: string): Promise<void>
  relayDisconnectAll(): Promise<void>
  relayForceResize(podKey: string, cols: number, rows: number): Promise<void>
  relayGetPodSize(podKey: string): Promise<Array<number>>
  relayGetStatus(podKey: string): Promise<string>
  relayIsRunnerDisconnected(podKey: string): Promise<boolean>
  relayOnPodDisconnected(onDisconnect: (err: unknown, arg: string) => void): Promise<void>
  relaySend(podKey: string, data: string): Promise<void>
  relaySendAcpCommand(podKey: string, command: string): Promise<void>
  relaySendResize(podKey: string, cols: number, rows: number): Promise<void>
  relaySubscribe(podKey: string, subscriptionId: string, relayUrl: string, token: string, onOutput: (err: unknown, arg: Array<number>) => void, onStatus: (err: unknown, arg: string) => void, onAcp: (err: unknown, arg: string) => void, onBound: (err: unknown, arg: number) => void, listenerLeaseId: string): Promise<void>
  relayUnsubscribe(podKey: string, subscriptionId: string): Promise<void>
  runnerAuthorizeRunner(requestBytes: Array<number>): Promise<Array<number>>
  runnerGetAuthStatus(requestBytes: Array<number>): Promise<Array<number>>
  ssoDiscoverConnect(request: Array<number>): Promise<Array<number>>
  ssoLdapAuthConnect(request: Array<number>): Promise<Array<number>>
  supportTicketAddSupportTicketMessageConnect(request: Array<number>): Promise<Array<number>>
  supportTicketAssociateAttachmentsConnect(request: Array<number>): Promise<Array<number>>
  supportTicketCreateSupportTicketConnect(request: Array<number>): Promise<Array<number>>
  supportTicketGetAttachmentUrlConnect(request: Array<number>): Promise<Array<number>>
  supportTicketGetSupportTicketConnect(request: Array<number>): Promise<Array<number>>
  supportTicketListSupportTicketsConnect(request: Array<number>): Promise<Array<number>>
  supportTicketPresignAttachmentUploadConnect(request: Array<number>): Promise<Array<number>>
  ticketAddAssigneeConnect(request: Array<number>): Promise<Array<number>>
  ticketAddLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketCreateLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketCreateTicketConnect(request: Array<number>): Promise<Array<number>>
  ticketDeleteLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketDeleteTicketConnect(request: Array<number>): Promise<Array<number>>
  ticketGetActiveTicketsConnect(request: Array<number>): Promise<Array<number>>
  ticketGetBoardConnect(request: Array<number>): Promise<Array<number>>
  ticketGetSubTicketsConnect(request: Array<number>): Promise<Array<number>>
  ticketGetTicketConnect(request: Array<number>): Promise<Array<number>>
  ticketGetTicketPods(slug: string, activeOnly: boolean | undefined | null): Promise<string>
  ticketListLabelsConnect(request: Array<number>): Promise<Array<number>>
  ticketListTicketsConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsCreateCommentConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsCreateRelationConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsDeleteCommentConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsDeleteRelationConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsLinkCommitConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsListCommentsConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsListCommitsConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsListMergeRequestsConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsListRelationsConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsUnlinkCommitConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsUpdateCommentConnect(request: Array<number>): Promise<Array<number>>
  ticketRemoveAssigneeConnect(request: Array<number>): Promise<Array<number>>
  ticketRemoveLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketUpdateLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketUpdateTicketConnect(request: Array<number>): Promise<Array<number>>
  ticketUpdateTicketStatusConnect(request: Array<number>): Promise<Array<number>>
  userChangePasswordConnect(request: Array<number>): Promise<Array<number>>
  userDeleteIdentityConnect(request: Array<number>): Promise<Array<number>>
  userGetMeConnect(request: Array<number>): Promise<Array<number>>
  userListIdentitiesConnect(request: Array<number>): Promise<Array<number>>
  userSearchUsersConnect(request: Array<number>): Promise<Array<number>>
  userUpdateMeConnect(request: Array<number>): Promise<Array<number>>
}
