// Package client provides gRPC registration for Runner.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/pkg/browser"

	"github.com/anthropics/agentsmesh/runner/internal/logger"
)

// ==================== Tailscale-style Interactive Registration ====================

// InteractiveRegistrationRequest contains parameters for interactive registration.
type InteractiveRegistrationRequest struct {
	ServerURL  string            // Base server URL (e.g., https://app.example.com)
	MachineKey string            // Unique machine key generated by Runner
	NodeID     string            // Optional node ID (hostname if empty)
	Labels     map[string]string // Optional labels
	Headless   bool              // If true, don't open browser automatically (for SSH/remote sessions)
}

// InteractiveRegistrationResult contains the result of interactive registration.
type InteractiveRegistrationResult struct {
	RunnerID      int64  `json:"runner_id"`
	Certificate   string `json:"certificate"`
	PrivateKey    string `json:"private_key"`
	CACertificate string `json:"ca_certificate"`
	GRPCEndpoint  string `json:"grpc_endpoint"`
	OrgSlug       string `json:"org_slug"`
}

// RequestAuthURL requests an authorization URL from the server.
// Step 1 of interactive registration - Runner requests auth URL.
func RequestAuthURL(ctx context.Context, req InteractiveRegistrationRequest) (authURL, authKey string, expiresIn int, err error) {
	log := logger.GRPC()
	requestURL := fmt.Sprintf("%s/api/v1/runners/grpc/auth-url", req.ServerURL)

	body := map[string]interface{}{
		"machine_key": req.MachineKey,
	}
	if req.NodeID != "" {
		body["node_id"] = req.NodeID
	}
	if len(req.Labels) > 0 {
		body["labels"] = req.Labels
	}

	bodyBytes, err := json.Marshal(body)
	if err != nil {
		log.Error("Failed to marshal auth URL request", "error", err)
		return "", "", 0, fmt.Errorf("failed to marshal request body: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, bytes.NewReader(bodyBytes))
	if err != nil {
		log.Error("Failed to create auth URL request", "error", err)
		return "", "", 0, fmt.Errorf("failed to create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(httpReq)
	if err != nil {
		log.Error("Auth URL request failed", "url", requestURL, "error", err)
		return "", "", 0, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		log.Error("Auth URL request returned non-OK status", "status", resp.StatusCode, "body", string(respBody))
		return "", "", 0, fmt.Errorf("server returned status %d: %s", resp.StatusCode, string(respBody))
	}

	var result struct {
		AuthURL   string `json:"auth_url"`
		AuthKey   string `json:"auth_key"`
		ExpiresIn int    `json:"expires_in"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		log.Error("Failed to decode auth URL response", "error", err)
		return "", "", 0, fmt.Errorf("failed to decode response: %w", err)
	}

	log.Info("Auth URL obtained", "expires_in", result.ExpiresIn)
	return result.AuthURL, result.AuthKey, result.ExpiresIn, nil
}

// AuthStatus represents the status of a pending authorization.
type AuthStatus struct {
	Status        string `json:"status"` // "pending", "authorized"
	RunnerID      int64  `json:"runner_id,omitempty"`
	Certificate   string `json:"certificate,omitempty"`
	PrivateKey    string `json:"private_key,omitempty"`
	CACertificate string `json:"ca_certificate,omitempty"`
	GRPCEndpoint  string `json:"grpc_endpoint,omitempty"`
	OrgSlug       string `json:"org_slug,omitempty"`
}

// GetAuthStatus polls the server for authorization status.
// Step 2 of interactive registration - Runner polls until authorized.
func GetAuthStatus(ctx context.Context, serverURL, authKey string) (*AuthStatus, error) {
	log := logger.GRPC()
	requestURL := fmt.Sprintf("%s/api/v1/runners/grpc/auth-status?key=%s", serverURL, authKey)

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		log.Error("Failed to create auth status request", "error", err)
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(httpReq)
	if err != nil {
		log.Error("Auth status request failed", "error", err)
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusNotFound {
		return nil, fmt.Errorf("authorization request not found or expired")
	}

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		log.Error("Auth status returned non-OK status", "status", resp.StatusCode, "body", string(respBody))
		return nil, fmt.Errorf("server returned status %d: %s", resp.StatusCode, string(respBody))
	}

	var status AuthStatus
	if err := json.NewDecoder(resp.Body).Decode(&status); err != nil {
		log.Error("Failed to decode auth status response", "error", err)
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &status, nil
}

// InteractiveRegister performs Tailscale-style interactive registration.
// Opens a browser for user authorization and polls for completion.
func InteractiveRegister(ctx context.Context, req InteractiveRegistrationRequest) (*InteractiveRegistrationResult, error) {
	log := logger.GRPC()

	// Step 1: Request auth URL
	authURL, authKey, expiresIn, err := RequestAuthURL(ctx, req)
	if err != nil {
		log.Error("Failed to request auth URL", "error", err)
		return nil, fmt.Errorf("failed to request auth URL: %w", err)
	}

	fmt.Printf("\nPlease open this link in your browser to authorize:\n\n  %s\n\n", authURL)
	fmt.Printf("The authorization link will expire in %d seconds\n\n", expiresIn)

	// Try to open browser (unless headless mode)
	if req.Headless {
		fmt.Printf("Running in headless mode - please copy the link above to your browser\n")
	} else {
		if err := browser.OpenURL(authURL); err != nil {
			fmt.Printf("Unable to open browser automatically, please copy the link manually\n")
		}
	}

	// Step 2: Poll for authorization status
	fmt.Print("Waiting for authorization")
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	timeout := time.After(time.Duration(expiresIn) * time.Second)

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-timeout:
			return nil, fmt.Errorf("authorization timeout after %d seconds", expiresIn)
		case <-ticker.C:
			fmt.Print(".")

			status, err := GetAuthStatus(ctx, req.ServerURL, authKey)
			if err != nil {
				// Log error but continue polling
				continue
			}

			if status.Status == "authorized" {
				fmt.Println("\n\n✅ Authorization successful!")
				return &InteractiveRegistrationResult{
					RunnerID:      status.RunnerID,
					Certificate:   status.Certificate,
					PrivateKey:    status.PrivateKey,
					CACertificate: status.CACertificate,
					GRPCEndpoint:  status.GRPCEndpoint,
					OrgSlug:       status.OrgSlug,
				}, nil
			}
		}
	}
}

// Note: Token registration is in grpc_registration_token.go
// Note: Certificate reactivation and renewal are in grpc_registration_renewal.go
