"""Next.js macro for AgentsMesh — ported from AIO with minimal tweaks.

For each `next_app()` call, produces four targets:
  :<name>               js_run_binary running `next build` (outputs `.next/`)
  :<name>_dev           devserver running `next dev`
  :<name>_start         devserver running `next start` against the build
  :<name>_start_binary  plain js_binary for the OCI image entrypoint

Used by clients/web and clients/web-admin. The Electron renderer bundle is
produced separately via build_defs/web/electron.bzl (which also calls
next_app under the hood).

Usage:
    load("@npm//clients/web:next/package_json.bzl", next_bin = "bin")
    load("//build_defs/web:next.bzl", "next_app")

    next_bin.next_binary(name = "next_js_binary")

    next_app(
        name = "next",
        srcs = [":src"],
        data = [
            "next.config.ts",
            "package.json",
            ":node_modules",
            "//:node_modules/agentsmesh-wasm",  # bazel-built wasm pkg
            ...
        ],
        next_js_binary = ":next_js_binary",
    )
"""

load("@aspect_bazel_lib//lib:copy_file.bzl", "copy_file")
load("@aspect_bazel_lib//lib:copy_to_directory.bzl", "copy_to_directory")
load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_run_binary", "js_run_devserver")
load("@bazel_skylib//rules:write_file.bzl", "write_file")

# The generated entry script the OCI image invokes. It re-execs the
# Next.js CLI's `start` subcommand against the built `.next/` tree,
# reading the port from PORT (default 3000). Keeping the launcher in
# JS — rather than a wrapper sh — means `js_binary`'s node
# `patch_node_fs` machinery still applies.
_START_JS_CONTENTS = """#!/usr/bin/env node
// @generated by //build_defs/web:next.bzl — do not edit by hand.
// Boots `next start` with the .next/ directory shipped alongside.
const { spawnSync } = require("child_process");

const here = __dirname;
const nextBin = require.resolve("next/dist/bin/next", { paths: [here] });
const port = process.env.PORT || "3000";
const result = spawnSync(process.execPath, [nextBin, "start", "-p", port], {
  cwd: here,
  stdio: "inherit",
  env: process.env,
});
process.exit(result.status === null ? 1 : result.status);
"""

def next_app(
        name,
        srcs,
        data,
        next_js_binary,
        next_build_out = ".next",
        **kwargs):
    """Build / dev / start targets for a Next.js app.

    Args:
        name: Base target name (`:name` is the production build).
        srcs: Application source files (usually `ts_project` outputs).
        data: Runtime deps (node_modules, config files).
        next_js_binary: `js_binary` pointing at Next's CLI, typically
            produced by `next_bin.next_binary(name = "next_js_binary")`.
        next_build_out: Build artifact dir, defaults to `.next`.
        **kwargs: Tags + visibility forwarded to all targets.
    """
    tags = kwargs.pop("tags", [])

    js_run_binary(
        name = name,
        # Next.js 16 defaults to Turbopack for `next build`, but Turbopack
        # fails in the Bazel sandbox with "Symlink package.json is invalid,
        # it points out of the filesystem root" (it walks up past the
        # execroot looking for node_modules). Force the legacy webpack
        # pipeline for the OCI build; dev mode still uses Turbopack via
        # `next dev` below.
        args = [
            "build",
            "--webpack",
        ],
        chdir = native.package_name(),
        mnemonic = "NextJsBuild",
        out_dirs = [next_build_out],
        progress_message = "Building Next.js application",
        srcs = srcs + data,
        # The dev-path build emits to the same `.next/` directory as
        # `next_standalone_app` below; running `bazel build //...`
        # asks Bazel to materialise both into one path → conflicting
        # actions. Tag manual so wildcard builds skip this; the dev
        # server (`:<name>_dev`) and explicit `bazel build :<name>`
        # invocations still work.
        tags = tags + ["manual"],
        tool = next_js_binary,
        **kwargs
    )

    js_run_devserver(
        name = "{}_dev".format(name),
        # Force webpack — Turbopack walks symlink chains looking for
        # `next/package.json` and bombs out with "We couldn't find the
        # Next.js package" inside the Bazel sandbox (the aspect_rules_js
        # symlink tree exits the execroot prematurely). Same issue
        # `next build` already mitigates with --webpack above.
        args = [
            "dev",
            "--webpack",
        ],
        chdir = native.package_name(),
        data = srcs + data,
        grant_sandbox_write_permissions = True,
        tags = tags,
        tool = next_js_binary,
        **kwargs
    )

    js_run_devserver(
        name = "{}_start".format(name),
        args = ["start"],
        chdir = native.package_name(),
        data = data + [name],
        # Manual because this target pulls `:name` (the dev build),
        # which is itself manual. Without the matching tag, wildcard
        # builds rope `:name` back in through this target's data.
        tags = tags + ["manual"],
        tool = next_js_binary,
        **kwargs
    )

    # Generate a tiny JS launcher so `js_binary` has a concrete entry
    # point. The script itself is deterministic — no stamping — and
    # lives in `bazel-bin/` under the package's own directory so
    # `js_image_layer` stages it next to `.next/` at /app/start.js.
    write_file(
        name = "{}_start_entry".format(name),
        out = "{}_start.js".format(name),
        content = _START_JS_CONTENTS.split("\n"),
        tags = tags + ["manual"],
    )

    js_binary(
        name = "{}_start_binary".format(name),
        chdir = native.package_name(),
        data = data + [name],
        entry_point = ":{}_start_entry".format(name),
        # OCI image pipeline uses `:next_image` instead; this binary
        # is here for symmetry with the non-Bazel `next start` flow.
        # Mark manual so wildcard builds don't pull `:name` through
        # this target's data closure.
        tags = tags + ["manual"],
        **kwargs
    )

# Standalone variant — produces a flat directory tree ready for `pkg_tar`
# into a distroless OCI image. We fork the upstream `nextjs_standalone_build`
# from aspect_rules_js v2.9.2 here (rather than calling it directly) for
# two reasons:
#   1. The upstream rule hard-codes `args = ["build"]`. Next 16's default
#      Turbopack pipeline crashes inside the Bazel sandbox with "Symlink
#      package.json is invalid, it points out of the filesystem root"
#      (same root cause that already forces `next_app` above to pass
#      `--webpack`). We need to thread `--webpack` through to the standalone
#      build too.
#   2. Vendoring the wrapper script (`build_defs/web/next_bazel_wrapper.mjs`)
#      keeps us self-contained — the wrapper deletes the pnpm-symlink
#      `node_modules` trees Next plants inside `.next/standalone/` so
#      Bazel's declared-output validation passes.
#
# The user's Next.js config MUST be named something other than
# `next.config.mjs` — we copy our wrapper to that path. We default to
# `next.config.bazel.mjs` for both apps.
def next_standalone_app(
        name,
        srcs,
        data,
        next_js_binary,
        config = "next.config.bazel.mjs",
        node_modules_runtime = None,
        **kwargs):
    """Build a Next.js standalone app + a packageable directory tree.

    Targets produced:
      :<name>             js_run_binary running `next build --webpack` (outputs
                          `.next/`, including `.next/standalone/` after
                          symlink fixup by next_bazel_wrapper.mjs).
      :<name>_server_dir  flat directory tree ready for pkg_tar / oci_image:
                            <pkg>/server.js
                            <pkg>/.next/static/**
                            <pkg>/public/**
                            <pkg>/node_modules/** (NFT-traced)
                            node_modules/** (workspace-level + runtime_deps)

    Args:
        name: base target name.
        srcs: TS/TSX/CSS/JSON source files.
        data: build-time deps (config files, full //:node_modules for NFT).
        next_js_binary: js_binary pointing at the Next CLI.
        config: path (relative to the package) of the user's Next.js config.
            MUST NOT be `next.config.mjs` — see module docstring above.
        node_modules_runtime: list of `//:node_modules/<pkg>` labels not
            included in the standalone tree (Next NFT misses dynamic
            requires). Defaults to next/react/react-dom; extend as smoke
            tests surface MODULE_NOT_FOUND at runtime.
        **kwargs: tags + visibility forwarded to all targets.
    """
    tags = kwargs.pop("tags", [])
    env = kwargs.pop("env", {})
    pkg = native.package_name()

    # Synthesise `next.config.mjs` from our vendored wrapper. The wrapper
    # reads the real config path from `NEXTJS_STANDALONE_CONFIG`.
    env["NEXTJS_STANDALONE_CONFIG"] = "$(locations {})".format(config)
    copy_file(
        name = "_{}.standalone_config_file".format(name),
        src = "//build_defs/web:next_bazel_wrapper.mjs",
        out = "next.config.mjs",
        visibility = ["//visibility:private"],
        tags = ["manual"],
    )

    js_run_binary(
        name = name,
        tool = next_js_binary,
        env = env,
        # `--webpack` mirrors `next_app` above — Turbopack walks symlinks
        # past the sandbox root. Re-evaluate when Turbopack ships a
        # sandbox-tolerant fs walker.
        args = [
            "build",
            "--webpack",
        ],
        srcs = srcs + data + [
            ":_{}.standalone_config_file".format(name),
            config,
        ],
        out_dirs = [".next"],
        chdir = pkg,
        mnemonic = "NextJsStandalone",
        progress_message = "Compile Next.js standalone app %{label}",
        tags = tags,
        **kwargs
    )

    runtime_deps = list(node_modules_runtime or [
        "//:node_modules/next",
        "//:node_modules/react",
        "//:node_modules/react-dom",
    ])

    # `replace_prefixes` flattens the standalone tree into the layer root.
    # Next.js plants server.js at `.next/standalone/<pkg>/server.js`; we
    # strip the `.next/standalone/` prefix so the tree's root mirrors the
    # monorepo layout (`<pkg>/server.js`). `.next/static/` and `public/`
    # are not packed into standalone by Next — copy them into place
    # under `<pkg>/`.
    #
    # `out = "app"` — the directory artifact is literally named `app` so
    # `next_oci.bzl`'s pkg_tar produces `<package>/app/<contents>` which
    # we then re-anchor at `/` with `package_dir = "/"` and a workspace
    # strip — yielding `/app/<contents>` in the final image.
    copy_to_directory(
        name = name + "_server_dir",
        out = "app",
        srcs = [name] + native.glob(["public/**"], allow_empty = True) + runtime_deps,
        # NFT-traced copies inside `.next/standalone/` overlap with the
        # `//:node_modules` aggregate (both contain e.g. `next/README.md`).
        # `copy_to_directory` rejects duplicates by default; allow them
        # so the standalone tree wins where it overrides.
        allow_overwrites = True,
        # Patterns are matched against each file's path relative to its
        # source. `:<name>` is a declared directory whose internal paths
        # start at the directory root (`static/`, `standalone/`, ...);
        # `glob("public/**")` returns paths under the package so they
        # carry a `public/` prefix. Listing both forms keeps the rule
        # robust against directory-artifact stripping behavior.
        include_srcs_patterns = [
            "public/**",
            "static/**",
            ".next/static/**",
            "standalone/**",
            ".next/standalone/**",
            "node_modules/**",
        ],
        exclude_srcs_patterns = [
            # `.aspect_rules_js/` is the pnpm virtual-store mirror —
            # node_modules/<pkg>/ are symlinks pointing in here, but
            # `copy_to_directory` already dereferences them, so the mirror
            # is redundant. Excluding it strips ~1 GB of multi-platform
            # native binaries (`@next/swc-*`, `@img/sharp-*`, `@swc/core-*`)
            # that the runtime container does not need.
            "node_modules/.aspect_rules_js/**",
        ],
        replace_prefixes = {
            "standalone/": "",
            ".next/standalone/": "",
            "static/": "{}/.next/static/".format(pkg),
            ".next/static/": "{}/.next/static/".format(pkg),
            "public/": "{}/public/".format(pkg),
        },
        visibility = ["//visibility:public"],
        tags = tags,
    )
