package agentpod

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"

	agentDomain "github.com/anthropics/agentsmesh/backend/internal/domain/agent"
	"github.com/anthropics/agentsmesh/backend/internal/domain/agentpod"
)

var (
	ErrPodNotFound           = errors.New("pod not found")
	ErrNoAvailableRunner     = errors.New("no available runner")
	ErrRunnerNotFound        = errors.New("runner not found")
	ErrRunnerOffline         = errors.New("runner is offline")
	// ErrSandboxAlreadyResumed is re-exported from domain for backward compatibility.
	ErrSandboxAlreadyResumed = agentpod.ErrSandboxAlreadyResumed
)

// PodService handles pod operations
type PodService struct {
	repo           agentpod.PodRepository
	eventPublisher EventPublisher
}

// SetEventPublisher sets the event publisher for the service
func (s *PodService) SetEventPublisher(publisher EventPublisher) {
	s.eventPublisher = publisher
}

// NewPodService creates a new pod service
func NewPodService(repo agentpod.PodRepository) *PodService {
	return &PodService{repo: repo}
}

// CreatePodRequest represents a pod creation request
type CreatePodRequest struct {
	OrganizationID    int64
	RunnerID          int64
	AgentSlug         string
	RepositoryID      *int64
	TicketID          *int64
	CreatedByID       int64
	Prompt            string
	Alias             *string
	BranchName        *string
	Model             string
	PermissionMode    string
	SkipPermissions   bool
	PreparationConfig *agentpod.PreparationConfig
	EnvVars        map[string]string
	ResolvedConfig agentDomain.ConfigValues

	// Resume related fields
	SessionID    string // Session ID for agent session management (generated by Backend)
	SourcePodKey string // Original pod key when creating via resume

	// Interaction mode: "pty" (default) or "acp"
	InteractionMode string

	// Perpetual mode: Runner auto-restarts the agent process on clean exit
	Perpetual bool
}

// CreatePod creates a new pod
func (s *PodService) CreatePod(ctx context.Context, req *CreatePodRequest) (*agentpod.Pod, error) {
	keyBytes := make([]byte, 4)
	if _, err := rand.Read(keyBytes); err != nil {
		return nil, err
	}
	randomSuffix := hex.EncodeToString(keyBytes)

	ticketPart := "standalone"
	if req.TicketID != nil {
		ticketPart = fmt.Sprintf("%d", *req.TicketID)
	}
	podKey := fmt.Sprintf("%d-%s-%s", req.CreatedByID, ticketPart, randomSuffix)

	var modelPtr *string
	if req.Model != "" {
		m := req.Model
		modelPtr = &m
	}

	var permissionModePtr *string
	if req.PermissionMode != "" {
		pm := req.PermissionMode
		permissionModePtr = &pm
	}
	// Handle session ID
	var sessionID *string
	if req.SessionID != "" {
		sessionID = &req.SessionID
	}

	// Handle source pod key for resume
	var sourcePodKey *string
	if req.SourcePodKey != "" {
		sourcePodKey = &req.SourcePodKey
	}

	// Resolve interaction mode with default
	interactionMode := req.InteractionMode
	if interactionMode == "" {
		interactionMode = agentpod.InteractionModePTY
	}

	pod := &agentpod.Pod{
		OrganizationID:      req.OrganizationID,
		PodKey:              podKey,
		RunnerID:            req.RunnerID,
		AgentSlug:           req.AgentSlug,
		RepositoryID:        req.RepositoryID,
		TicketID:            req.TicketID,
		CreatedByID:         req.CreatedByID,
		Status:              agentpod.StatusInitializing,
		AgentStatus:         agentpod.AgentStatusIdle,
		Prompt:              req.Prompt,
		Alias:               req.Alias,
		BranchName:          req.BranchName,
		Model:          modelPtr,
		PermissionMode: permissionModePtr,
		SessionID:      sessionID,
		SourcePodKey:   sourcePodKey,
		InteractionMode:     interactionMode,
		Perpetual:           req.Perpetual,
		ResolvedConfig:      req.ResolvedConfig,
	}

	if err := s.repo.Create(ctx, pod); err != nil {
		return nil, err
	}

	slog.InfoContext(ctx, "pod created", "pod_key", pod.PodKey, "org_id", pod.OrganizationID, "agent_slug", pod.AgentSlug, "runner_id", pod.RunnerID)

	// NOTE: current_pods increment is handled by PodCoordinator.CreatePod(),
	// which runs only when a command is actually sent to Runner.
	// Do NOT increment here to avoid double-counting.

	return pod, nil
}

// CreatePodForTicket creates a pod with ticket context
func (s *PodService) CreatePodForTicket(ctx context.Context, req *CreatePodRequest) (*agentpod.Pod, error) {
	if req.TicketID == nil {
		return nil, errors.New("ticket_id is required")
	}

	slug, title, err := s.repo.GetTicketByID(ctx, *req.TicketID)
	if err != nil {
		return nil, fmt.Errorf("ticket not found: %w", err)
	}

	if req.Prompt == "" {
		req.Prompt = fmt.Sprintf("Working on ticket: %s\nTitle: %s", slug, title)
	}

	return s.CreatePod(ctx, req)
}
