package apierr

const (
	AUTH_REQUIRED            = "AUTH_REQUIRED"
	INVALID_TOKEN            = "INVALID_TOKEN"
	TOKEN_EXPIRED            = "TOKEN_EXPIRED"
	API_KEY_EXPIRED          = "API_KEY_EXPIRED"
	ACCESS_DENIED            = "ACCESS_DENIED"
	ADMIN_REQUIRED           = "ADMIN_REQUIRED"
	OWNER_REQUIRED           = "OWNER_REQUIRED"
	INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
	NOT_ORG_MEMBER           = "NOT_ORG_MEMBER"
	SYSTEM_ADMIN_REQUIRED    = "SYSTEM_ADMIN_REQUIRED"
	ACCOUNT_DISABLED         = "ACCOUNT_DISABLED"
	SSO_REQUIRED             = "SSO_REQUIRED"
	INSUFFICIENT_SCOPE       = "INSUFFICIENT_SCOPE"
	API_KEY_DISABLED         = "API_KEY_DISABLED"
	API_KEY_ORG_MISMATCH     = "API_KEY_ORG_MISMATCH"
)

const (
	CONCURRENT_POD_QUOTA_EXCEEDED = "CONCURRENT_POD_QUOTA_EXCEEDED"
	SUBSCRIPTION_FROZEN           = "SUBSCRIPTION_FROZEN"
	NO_AVAILABLE_SEATS            = "NO_AVAILABLE_SEATS"
	RUNNER_QUOTA_EXCEEDED         = "RUNNER_QUOTA_EXCEEDED"
	REPOSITORY_QUOTA_EXCEEDED     = "REPOSITORY_QUOTA_EXCEEDED"
	SEAT_LIMIT_EXCEEDED           = "SEAT_LIMIT_EXCEEDED"
	MOCK_PAYMENT_DISABLED         = "MOCK_PAYMENT_DISABLED"
)

const (
	VALIDATION_FAILED = "VALIDATION_FAILED"
	INVALID_INPUT     = "INVALID_INPUT"
	MISSING_REQUIRED  = "MISSING_REQUIRED"
)

const (
	MISSING_RUNNER_ID          = "MISSING_RUNNER_ID"
	MISSING_AGENT_SLUG         = "MISSING_AGENT_SLUG"
	SOURCE_POD_NOT_FOUND       = "SOURCE_POD_NOT_FOUND"
	SOURCE_POD_ALREADY_RESUMED = "SOURCE_POD_ALREADY_RESUMED"
	SOURCE_POD_NOT_TERMINATED  = "SOURCE_POD_NOT_TERMINATED"
	RESUME_RUNNER_MISMATCH     = "RESUME_RUNNER_MISMATCH"
	SOURCE_POD_ACCESS_DENIED   = "SOURCE_POD_ACCESS_DENIED"
	SANDBOX_ALREADY_RESUMED    = "SANDBOX_ALREADY_RESUMED"
	NO_AVAILABLE_RUNNER        = "NO_AVAILABLE_RUNNER"
	POD_CONFIG_BUILD_FAILED    = "POD_CONFIG_BUILD_FAILED"
	RUNNER_DISPATCH_FAILED     = "RUNNER_DISPATCH_FAILED"
	UNSUPPORTED_INTERACTION_MODE = "UNSUPPORTED_INTERACTION_MODE"
)

const (
	RESOURCE_NOT_FOUND  = "RESOURCE_NOT_FOUND"
	ALREADY_EXISTS      = "ALREADY_EXISTS"
	HAS_REFERENCES      = "HAS_REFERENCES"
	INTERNAL_ERROR      = "INTERNAL_ERROR"
	SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
	NOT_IMPLEMENTED     = "NOT_IMPLEMENTED"
	RATE_LIMITED        = "RATE_LIMITED"
	CAPACITY_EXCEEDED   = "CAPACITY_EXCEEDED"
	PAYLOAD_TOO_LARGE   = "PAYLOAD_TOO_LARGE"
	UNSUPPORTED_MEDIA   = "UNSUPPORTED_MEDIA"
	QUOTA_EXCEEDED      = "QUOTA_EXCEEDED"
)
